In [ ]:
import pandas as pd

# Try reading the CSV file using 'latin-1' encoding
df = pd.read_csv('/content/zomato.csv', encoding='latin-1')
# If 'latin-1' doesn't work, try other encodings like 'ISO-8859-1', 'cp1252', etc.
# df = pd.read_csv('/content/zomato.csv', encoding='ISO-8859-1')

df.head()
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9551 entries, 0 to 9550
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant ID         9551 non-null   int64
 1   Restaurant Name       9551 non-null   object
 2   Country Code          9551 non-null   int64
 3   City                  9551 non-null   object
 4   Address               9551 non-null   object
 5   Locality              9551 non-null   object
 6   Locality Verbose      9551 non-null   object
 7   Longitude             9551 non-null   float64
 8   Latitude              9551 non-null   float64
 9   Cuisines              9542 non-null   object
 10  Average Cost for two  9551 non-null   int64
 11  Currency              9551 non-null   object
 12  Has Table booking     9551 non-null   object
 13  Has Online delivery   9551 non-null   object
 14  Is delivering now     9551 non-null   object
 15  Switch to order menu  9551 non-null   object
 16  Price range           9551 non-null   int64
 17  Aggregate rating      9551 non-null   float64
 18  Rating color          9551 non-null   object
 19  Rating text           9551 non-null   object
 20  Votes                 9551 non-null   int64
dtypes: float64(3), int64(5), object(13)
memory usage: 1.5+ MB

,Restaurant ID,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9.551000e+03,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,9.051128e+06,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,8.791521e+06,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,5.300000e+01,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,3.019625e+05,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,6.004089e+06,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.835229e+07,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,1.850065e+07,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [ ]:
df.drop([
    'Restaurant ID', 'Address', 'Locality', 'Locality Verbose',
    'Longitude', 'Latitude', 'Switch to order menu'
], axis=1, inplace=True)

In [ ]:
df = df[df['Cuisines'].notnull()]
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [ ]:
df['cuisines'] = df['cuisines'].apply(lambda x: str(x).split(',')[0].strip())
df['has_table_booking'] = df['has_table_booking'].map({'Yes': 1, 'No': 0})
df['has_online_delivery'] = df['has_online_delivery'].map({'Yes': 1, 'No': 0})

In [ ]:
df['price_category'] = pd.cut(df['average_cost_for_two'],
                              bins=[0, 300, 800, 2000, 5000],
                              labels=['Budget', 'Mid-range', 'Expensive', 'Luxury'])

In [ ]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
Index: 9542 entries, 0 to 9550
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   restaurant_name       9542 non-null   object
 1   country_code          9542 non-null   int64
 2   city                  9542 non-null   object
 3   cuisines              9542 non-null   object
 4   average_cost_for_two  9542 non-null   int64
 5   currency              9542 non-null   object
 6   has_table_booking     9542 non-null   int64
 7   has_online_delivery   9542 non-null   int64
 8   is_delivering_now     9542 non-null   object
 9   price_range           9542 non-null   int64
 10  aggregate_rating      9542 non-null   float64
 11  rating_color          9542 non-null   object
 12  rating_text           9542 non-null   object
 13  votes                 9542 non-null   int64
 14  price_category        9495 non-null   category
dtypes: category(1), float64(1), int64(6), object(7)
memory usage: 1.1+ MB

,restaurant_name,country_code,city,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,price_range,aggregate_rating,rating_color,rating_text,votes,price_category
0,Le Petit Souffle,162,Makati City,French,1100,Botswana Pula(P),1,0,No,3,4.8,Dark Green,Excellent,314,Expensive
1,Izakaya Kikufuji,162,Makati City,Japanese,1200,Botswana Pula(P),1,0,No,3,4.5,Dark Green,Excellent,591,Expensive
2,Heat - Edsa Shangri-La,162,Mandaluyong City,Seafood,4000,Botswana Pula(P),1,0,No,4,4.4,Green,Very Good,270,Luxury
3,Ooma,162,Mandaluyong City,Japanese,1500,Botswana Pula(P),0,0,No,4,4.9,Dark Green,Excellent,365,Expensive
4,Sambo Kojin,162,Mandaluyong City,Japanese,1500,Botswana Pula(P),1,0,No,4,4.8,Dark Green,Excellent,229,Expensive

In [ ]:
# Save the cleaned dataset to a CSV file
df.to_csv('/content/cleaned_zomato.csv', index=False)